version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: ls -Al

      - run:
          name: Install jq
          command: |
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
            sudo chmod +rx jq-linux64
            sudo mv jq-linux64 /usr/local/bin/jq

      - run:
          name: Install doctl
          command: |
            wget https://github.com/digitalocean/doctl/releases/download/v1.45.1/doctl-1.45.1-linux-amd64.tar.gz
            tar xf doctl-1.45.1-linux-amd64.tar.gz
            sudo mv doctl /usr/local/bin
            doctl auth init --access-token $DO_ACCESS_TOKEN

      - run:
          name: Deploy
          command: |
            sudo chmod +rx bin/deploy.sh
            ./bin/deploy.sh $CIRCLE_BRANCH $CIRCLE_BUILD_NUM $DO_IMAGE $DO_REGION $DO_SIZE

workflows:
  version: 2
  setup:
    jobs:
      - build
